version: '3'
services:
  django:
    image: django:latest
    container_name: django_app
    build:
      context: ./rtbolidozor_backend
      dockerfile: Dockerfile_guicorn

    volumes:
      - /data/bolidozor/django:/data
      - ./rtbolidozor_backend/:/app
      - ./rtbolidozor_tools/:/tools
      - /storage/bolidozor:/storage
    #ports:
    #  - 8011:8001
    depends_on:
      - redis
      - db
    env_file:
      - /data/bolidozor/.env
    networks:
      - internal_net

  websocket:
    image: django:latest
    container_name: websocket_app
    build:
      context: ./rtbolidozor_backend
      dockerfile: Dockerfile_daphne
    volumes:
      - /data/bolidozor/websocket:/data
      - ./rtbolidozor_backend/:/app
    #ports:
    #  - 8012:8001
    depends_on:
      - redis
      - db
    env_file:
      - /data/bolidozor/.env
    networks:
      - internal_net
    command: daphne -b 0.0.0.0 -p 8001 rtbolidozor_backend.asgi:application

  worker:
    image: django:latest
    container_name: django_q
    build:
      context: ./rtbolidozor_backend
      dockerfile: Dockerfile_guicorn

    volumes:
      - /data/bolidozor/django:/data
      - ./rtbolidozor_backend/:/app
      - ./rtbolidozor_tools/:/tools
      - /storage/bolidozor:/storage
    #ports:
    #  - 8011:8001
    depends_on:
      - redis
      - db
    env_file:
      - /data/bolidozor/.env
    networks:
      - internal_net
    command: python3 manage.py qcluster


  vue:
    image: node:latest
    container_name: vue_app
    build:
      context: ./rtbolidozor_frontend
      dockerfile: Dockerfile_vue
    #command: npm run build
    volumes:
    #  #- /data/bolidozor/vue:/app
      - ./rtbolidozor_frontend/src:/usr/src/app/src
    #ports:
    #  - 8010:8080
    env_file:
      - /data/bolidozor/.env
    networks:
      - internal_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /data/bolidozor/redis:/root/redis
      - /data/bolidozor/redis.conf:/usr/local/etc/redis/redis.conf
    #ports:
    #  - "6333:6379"
    networks:
      - internal_net

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - /data/bolidozor/postgres:/var/lib/postgresql/data
    env_file:
      - /data/bolidozor/.env
#    ports:
#      - "5432:5432"
    networks:
      - internal_net

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ./rtbolidozor_nginx
      dockerfile: Dockerfile_nginx
    ports:
      - 8888:8888
    depends_on:
      - django
      - vue
      - websocket
    networks:
      - internal_net


  # For internal network debuging purposes
  #network_tools:
  #  image: busybox
  #  container_name: network_tools
  #  command: ["sh", "-c", "while true; do sleep 3600; done"]
  #  networks:
  #    - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  django_data:
  websocket_data:
  vue_data:
  redis_data:
  postgres_data:
