# Generated by Django 3.2.10 on 2024-09-18 00:08

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='UUIDMixin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuidmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rtbolidozor_backend.uuidmixin')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hash', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
                ('indexed', models.BooleanField(default=False)),
            ],
            bases=('rtbolidozor_backend.uuidmixin',),
        ),
        migrations.CreateModel(
            name='MultiStationEvent',
            fields=[
                ('uuidmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rtbolidozor_backend.uuidmixin')),
                ('timestamp', models.DateTimeField()),
            ],
            bases=('rtbolidozor_backend.uuidmixin',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('pending', 'Pending'), ('error', 'Error'), ('replaced', 'Replaced')], default='pending', max_length=20)),
                ('last_active', models.DateTimeField(default='2000-01-01 00:00:00')),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='rtbolidozor_backend.observatory')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Snapshot timestamp, start of the observation')),
                ('duration', models.FloatField(blank=True, help_text='Duration of the snapshot in seconds', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='rtbolidozor_backend.station')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('obs_start_time', models.DateTimeField(help_text='System start time of the event')),
                ('peak_frequency', models.FloatField(null=True)),
                ('magnitude', models.FloatField(null=True)),
                ('duration', models.FloatField(help_text='Duration of the event in seconds', null=True)),
                ('corrected_time_flag', models.BooleanField(default=False, help_text='Flag indicating if the time is corrected', null=True)),
                ('corrected_start_time', models.DateTimeField(help_text='Corrected start time of the event', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rtbolidozor_backend.station')),
            ],
        ),
        migrations.CreateModel(
            name='BolidozorUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('identifier', 'observatory'), name='unique_station'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='snap_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rtbolidozor_backend.file'),
        ),
        migrations.AddField(
            model_name='multistationevent',
            name='events',
            field=models.ManyToManyField(related_name='other_stations', to='rtbolidozor_backend.Event'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='rtbolidozor_name_5348e0_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='met_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_met', to='rtbolidozor_backend.file'),
        ),
        migrations.AddField(
            model_name='event',
            name='raw_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_raw', to='rtbolidozor_backend.file'),
        ),
    ]
