# Generated by Django 3.2.10 on 2026-06-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Cached Stats',
            },
        ),
        migrations.AlterField(
            model_name='station',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
