# Generated by Django 5.0.7 on 2024-08-01 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtbolidozor_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UUIDMixin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bolidozoruser",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="bolidozoruser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="bolidozoruser",
            name="twitter_handle",
        ),
    ]
