# Generated by Django 5.0.7 on 2024-08-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rtbolidozor_backend",
            "0002_uuidmixin_remove_bolidozoruser_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("pending", "Pending"),
                    ("error", "Error"),
                    ("replaced", "Replaced"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
