# Generated by Django 3.2.10 on 2024-08-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0003_station_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_start_time', models.DateTimeField(help_text='System start time of the event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_frequency', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('duration', models.FloatField(help_text='Duration of the event in seconds')),
                ('corrected_time_flag', models.BooleanField(default=False, help_text='Flag indicating if the time is corrected')),
                ('corrected_start_time', models.DateTimeField(help_text='Corrected start time of the event')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='last_active',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='rtbolidozor_name_5348e0_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rtbolidozor_backend.file'),
        ),
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='rtbolidozor_backend.eventmetadata'),
        ),
        migrations.AddField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rtbolidozor_backend.station'),
        ),
    ]
