# Generated by Django 3.2.10 on 2024-08-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0004_auto_20240807_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventMetadata',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
