# Generated by Django 3.2.10 on 2024-08-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0006_auto_20240807_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='file_record',
        ),
        migrations.AddField(
            model_name='event',
            name='met_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_met', to='rtbolidozor_backend.file'),
        ),
        migrations.AddField(
            model_name='event',
            name='raw_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_raw', to='rtbolidozor_backend.file'),
        ),
    ]
