# Generated by Django 3.2.10 on 2024-08-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0007_auto_20240807_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStationEvent',
            fields=[
                ('uuidmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rtbolidozor_backend.uuidmixin')),
                ('timestamp', models.DateTimeField()),
            ],
            bases=('rtbolidozor_backend.uuidmixin',),
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='uuidmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='metadata',
        ),
        migrations.AddField(
            model_name='event',
            name='corrected_start_time',
            field=models.DateTimeField(help_text='Corrected start time of the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='corrected_time_flag',
            field=models.BooleanField(default=False, help_text='Flag indicating if the time is corrected', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.FloatField(help_text='Duration of the event in seconds', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='peak_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('identifier', 'observatory'), name='unique_station'),
        ),
        migrations.DeleteModel(
            name='EventMetadata',
        ),
        migrations.AddField(
            model_name='multistationevent',
            name='events',
            field=models.ManyToManyField(related_name='other_stations', to='rtbolidozor_backend.Event'),
        ),
    ]
