# Generated by Django 3.2.10 on 2024-09-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtbolidozor_backend', '0008_auto_20240808_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('uuidmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rtbolidozor_backend.uuidmixin')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Snapshot timestamp, start of the observation')),
                ('duration', models.FloatField(blank=True, help_text='Duration of the snapshot in seconds', null=True)),
                ('snap_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='rtbolidozor_backend.file')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rtbolidozor_backend.station')),
            ],
            bases=('rtbolidozor_backend.uuidmixin',),
        ),
    ]
