# Dockerfile for Django backend
FROM python:3.11.4-slim-buster

# Set environment variables

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Collect static files
#RUN python3 manage.py collectstatic --noinput

# Expose port 8000 for Gunicorn
# EXPOSE 8001

# Run Gunicorn
#CMD ["python", "manage.py", "runserver" "0.0.0.0:8001"]
#CMD ["gunicorn", "rtbolidozor_backend.wsgi:application", "--bind", "0.0.0.0:8001"]
CMD ["gunicorn", "rtbolidozor_backend.wsgi:application", "--bind", "0.0.0.0:8001" "--reload"]
