user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    #keepalive_timeout  65;

    upstream django {
        server django_app:8001;
    }

    upstream websocket {
        server websocket_app:8001;
    }

    upstream vue {
        server vue_app:8080;
    }

    server {
        listen 8888;

        # Ignorování specifických požadavků
        #location ~* ^/event/* {
        #    return 204;  # 204 No Content
        #}



        location / {
            proxy_pass http://vue_app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 600s;
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
        }


        location /api {
            proxy_pass http://django$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /event {
            proxy_pass http://django$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin {
            proxy_pass http://django$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            proxy_pass http://django$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws {
            proxy_pass http://websocket$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


      #  location / {
     #       proxy_pass http://vue$request_uri;
    #        proxy_set_header Host $host;
   #         proxy_set_header X-Real-IP $remote_addr;
  #          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 #           proxy_set_header X-Forwarded-Proto $scheme;
#        }

    access_log /var/log/nginx/rtbolidozor_access.log;
    error_log /var/log/nginx/rtbolidozor_error.log;

    }
}
